name: coverage
on:
  push:
    branches: 
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: ncruces/go-coverage-report@v0
