name: hello-world
on:
  push:
    paths:
      - '!README.md' # khong chay khi file readme thay doi
      - '!docs/**' # khong chay khi toan bo folder docs thay doi, tat ca cac con trong do luon
      - '**.js' # chay khi co su thay doi o file js o tat ca cac folder
    branches: 
      - 'main' # chay khi co su thay doi o nhanh main
      - 'release/**' # khong chay khi co su thay doi o nhanh realease va tat ca nhanh con
      - '!dev/**' 
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY = $(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is TODAY