name: pr-action
on:
  push:
    paths:
      - '!README.md' # khong chay khi file readme thay doi
      - '!docs/**' # khong chay khi toan bo folder docs thay doi, tat ca cac con trong do luon
      - '**.js' # chay khi co su thay doi o file js o tat ca cac folder
    branches: 
      - 'main' # chay khi co su thay doi o nhanh main
      - 'release/**' # khong chay khi co su thay doi o nhanh realease va tat ca nhanh con
      - '!dev/**' 
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:
jobs:
  run-pr-action:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 0
          labels: "do not build"
      - run: echo This is has a pull request